services:
  cch-server:
    image: ghcr.io/stoodcoronet/cch-server:latest
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - HANDY_MASTER_SECRET=${HANDY_MASTER_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PORT=3005
    volumes:
      - cch-data:/data
    restart: unless-stopped

volumes:
  cch-data:
